### Product
GET http://localhost:3000/products

###

GET http://localhost:3000/products/6523cc8896270bbb2618b6cb

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "Product_Name": "กาแฟตึง",
    "Product_Type": "Coffee",
    "Product_IsHot": true,
    "Product_IsCold": true,
    "Product_IsFrappe": false,
    "Product_Detail": "กาแฟตึงตึง",
    "Product_Img": "https://www.cafe-amazon.com/BackEnd/TempProducts/9fc439a9db874ea3ad33cd3e04ce5aff.png"
}

### ProductType

POST http://localhost:3000/productTypes
Content-Type: application/json

{
    "ProductType_Name": "Tea"
}

###

GET http://localhost:3000/productTypes

###

GET http://localhost:3000/productTypes/6523c71f874858dcc18e2edc

###

DELETE http://localhost:3000/productTypes/6523b111799e1ee07959ff46

###

PATCH http://localhost:3000/productTypes/6523b1ba799e1ee07959ff49
Content-Type: application/json

{
    "ProductType_Id": 25,
    "ProductType_Name": "Tea"
}